### ISSUE TITLE
re-compile or re-install ?

### ISSUE THREAD

**Issue by malachib** [fardog/node-chromecast-osx-audio#14]
Getting this:

```
/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: The module '/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at bindings (/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/lame/lib/bindings.js:1:99)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```

I tried my best to recompile... but my best wasn't good enough.  Running nodejs 9.4.0.  Any suggestions?

**Comment by fardog** [comment]
@malachib unfortunately I don't maintain this library any longer (I don't have a mac on which to test it) but: did you upgrade your local version of node after the library was installed? if so, you should probably just remove and reinstall, which will force a full rebuild.

force a removal and rebuild with an `npm remove -g chromecast-osx-audio && npm install -g chromecast-osx-audio`; will _probably_ do it. otherwise it might need some sort of upgrade to work with the latest 9.x of nodejs. report back, and i'll update labels on this issue in hopes that someone who can work on it will pick it up.

**Comment by malachib** [comment]
@fardog OK, well thank you for the fast response - and your recommendation seems to be exactly what was needed - seems to work well! [can't be 100% sure because of an unrelated chromecast bug] - I feel dumb, but thankful!  lol
