### ISSUE TITLE
Error when running chrome cast command

### ISSUE THREAD

**Issue by thevolcanomanishere** [fardog/node-chromecast-osx-audio#4]
Output from terminal. I also have Soundflower installed and that is set as the audio source.

AM-MacBook-Pro:~ alexmcgonagle$ chromecast
found device "Crustcast" at 192.168.0.11:8009
Connecting to device 'Crustcast'
connected, launching app ...
streaming at http://192.168.0.23:3000/stream.mp3
app "Default Media Receiver" launched, loading media http://192.168.0.23:3000/stream.mp3 ...

/usr/local/lib/node_modules/chromecast-osx-audio/lib/index.js:72
          console.log('status broadcast playerState=%s', status.playerState);
                                                               ^
TypeError: Cannot read property 'playerState' of undefined
    at DefaultMediaReceiver.<anonymous> (/usr/local/lib/node_modules/chromecast-osx-audio/lib/index.js:72:64)
    at DefaultMediaReceiver.emit (events.js:95:17)
    at MediaController.onstatus (/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/castv2-client/lib/senders/default-media-receiver.js:16:10)
    at MediaController.emit (events.js:95:17)
    at MediaController.onmessage (/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/castv2-client/lib/controllers/media.js:19:12)
    at MediaController.emit (events.js:117:20)
    at Channel.onmessage (/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/castv2-client/lib/controllers/controller.js:16:10)
    at Channel.emit (events.js:98:17)
    at Client.onmessage (/usr/local/lib/node_modules/chromecast-osx-audio/node_modules/castv2-client/node_modules/castv2/lib/channel.js:23:10)
    at Client.emit (events.js:117:20)

**Comment by j15e** [comment]
Same issue here with ChromeCast version 27946, but after updating to 31432, now it works! All you have to do to update is to reboot the Chromecast from the Chromecast remote app.

**Comment by fardog** [comment]
Hi @thevolcanomanishere; please try the fix suggested by @j15e, and see if this issue persists; usually this error is because communication has failed with the chromecast at the time that the audio stream is picked up; I've never been able to replicate it, unfortunately.

Please re-open this issue if the problem persists.
